// Catálogo semilla de carreras. Valores aproximados (desnivel, clima típico):
// verifícalos en la web oficial de cada carrera antes de tomar decisiones.

export interface Race {
  id: string;
  name: string;
  city: string;
  country: string;
  distanceKm: number;
  month: number; // 1-12 mes habitual
  typicalDate?: string; // próxima edición estimada (verificar)
  elevationGainM: number;
  elevationLossM: number;
  temperatureC: number; // temperatura típica a la hora de salida
  profile: "muy rápido" | "rápido" | "ondulado" | "exigente";
  highlights: string[];
  website: string;
}

const M = 42.195;
const H = 21.0975;

export const RACES: Race[] = [
  {
    id: "valencia-maraton",
    name: "Maratón Valencia",
    city: "Valencia",
    country: "España",
    distanceKm: M,
    month: 12,
    typicalDate: "2026-12-06",
    elevationGainM: 40,
    elevationLossM: 40,
    temperatureC: 12,
    profile: "muy rápido",
    highlights: ["Uno de los maratones más rápidos del mundo", "Llegada sobre el agua en la Ciudad de las Artes", "Ambiente espectacular en todo el recorrido"],
    website: "https://www.valenciaciudaddelrunning.com",
  },
  {
    id: "sevilla-maraton",
    name: "Zurich Maratón de Sevilla",
    city: "Sevilla",
    country: "España",
    distanceKm: M,
    month: 2,
    typicalDate: "2027-02-21",
    elevationGainM: 30,
    elevationLossM: 30,
    temperatureC: 11,
    profile: "muy rápido",
    highlights: ["El más llano de Europa", "Ideal para marca personal", "Clima suave en febrero"],
    website: "https://www.zurichmaratonsevilla.es",
  },
  {
    id: "barcelona-maraton",
    name: "Zurich Marató Barcelona",
    city: "Barcelona",
    country: "España",
    distanceKm: M,
    month: 3,
    typicalDate: "2027-03-14",
    elevationGainM: 130,
    elevationLossM: 130,
    temperatureC: 14,
    profile: "rápido",
    highlights: ["Recorrido por Sagrada Familia y Diagonal", "Ligeras ondulaciones", "Puede hacer calor al final"],
    website: "https://www.zurichmaratobarcelona.es",
  },
  {
    id: "madrid-maraton",
    name: "Maratón de Madrid",
    city: "Madrid",
    country: "España",
    distanceKm: M,
    month: 4,
    typicalDate: "2027-04-25",
    elevationGainM: 320,
    elevationLossM: 320,
    temperatureC: 15,
    profile: "exigente",
    highlights: ["Desnivel notable, sobre todo en la segunda mitad", "Final en el Retiro", "Altitud ~650 m"],
    website: "https://www.zurichmaratonmadrid.es",
  },
  {
    id: "malaga-maraton",
    name: "Maratón de Málaga",
    city: "Málaga",
    country: "España",
    distanceKm: M,
    month: 12,
    typicalDate: "2026-12-13",
    elevationGainM: 50,
    elevationLossM: 50,
    temperatureC: 14,
    profile: "rápido",
    highlights: ["Llano junto al mar", "Viento posible en el paseo marítimo"],
    website: "https://www.generalimalagamaraton.com",
  },
  {
    id: "donostia-maraton",
    name: "Maratón de Donostia",
    city: "San Sebastián",
    country: "España",
    distanceKm: M,
    month: 11,
    typicalDate: "2026-11-29",
    elevationGainM: 60,
    elevationLossM: 60,
    temperatureC: 10,
    profile: "rápido",
    highlights: ["Dos vueltas por la ciudad", "Posible lluvia y viento"],
    website: "https://www.maratondonostia.com",
  },
  {
    id: "berlin-marathon",
    name: "BMW Berlin Marathon",
    city: "Berlín",
    country: "Alemania",
    distanceKm: M,
    month: 9,
    typicalDate: "2027-09-26",
    elevationGainM: 70,
    elevationLossM: 70,
    temperatureC: 14,
    profile: "muy rápido",
    highlights: ["Major. Escenario de récords del mundo", "Paso por la Puerta de Brandeburgo", "Sorteo de dorsales"],
    website: "https://www.bmw-berlin-marathon.com",
  },
  {
    id: "london-marathon",
    name: "TCS London Marathon",
    city: "Londres",
    country: "Reino Unido",
    distanceKm: M,
    month: 4,
    typicalDate: "2027-04-25",
    elevationGainM: 120,
    elevationLossM: 140,
    temperatureC: 12,
    profile: "rápido",
    highlights: ["Major", "Tower Bridge y The Mall", "Sorteo muy competido"],
    website: "https://www.tcslondonmarathon.com",
  },
  {
    id: "chicago-marathon",
    name: "Bank of America Chicago Marathon",
    city: "Chicago",
    country: "EE. UU.",
    distanceKm: M,
    month: 10,
    typicalDate: "2027-10-10",
    elevationGainM: 70,
    elevationLossM: 70,
    temperatureC: 13,
    profile: "muy rápido",
    highlights: ["Major", "Muy llano", "Los rascacielos afectan al GPS"],
    website: "https://www.chicagomarathon.com",
  },
  {
    id: "nyc-marathon",
    name: "TCS New York City Marathon",
    city: "Nueva York",
    country: "EE. UU.",
    distanceKm: M,
    month: 11,
    typicalDate: "2026-11-01",
    elevationGainM: 250,
    elevationLossM: 250,
    temperatureC: 10,
    profile: "exigente",
    highlights: ["Major", "Cinco distritos y cinco puentes", "Subida en la 5ª Avenida al final"],
    website: "https://www.nyrr.org/tcsnycmarathon",
  },
  {
    id: "boston-marathon",
    name: "Boston Marathon",
    city: "Boston",
    country: "EE. UU.",
    distanceKm: M,
    month: 4,
    typicalDate: "2027-04-19",
    elevationGainM: 250,
    elevationLossM: 390,
    temperatureC: 12,
    profile: "exigente",
    highlights: ["Major. Requiere marca mínima", "Bajada neta que castiga cuádriceps", "Heartbreak Hill (km 32)"],
    website: "https://www.baa.org",
  },
  {
    id: "tokyo-marathon",
    name: "Tokyo Marathon",
    city: "Tokio",
    country: "Japón",
    distanceKm: M,
    month: 3,
    typicalDate: "2027-03-07",
    elevationGainM: 40,
    elevationLossM: 80,
    temperatureC: 8,
    profile: "muy rápido",
    highlights: ["Major", "Muy llano y frío", "Organización impecable"],
    website: "https://www.marathon.tokyo",
  },
  {
    id: "paris-marathon",
    name: "Schneider Electric Marathon de Paris",
    city: "París",
    country: "Francia",
    distanceKm: M,
    month: 4,
    typicalDate: "2027-04-11",
    elevationGainM: 150,
    elevationLossM: 150,
    temperatureC: 11,
    profile: "rápido",
    highlights: ["Campos Elíseos", "Túneles junto al Sena", "Bois de Vincennes y Bois de Boulogne"],
    website: "https://www.schneiderelectricparismarathon.com",
  },
  {
    id: "valencia-media",
    name: "Medio Maratón Valencia",
    city: "Valencia",
    country: "España",
    distanceKm: H,
    month: 10,
    typicalDate: "2026-10-25",
    elevationGainM: 20,
    elevationLossM: 20,
    temperatureC: 17,
    profile: "muy rápido",
    highlights: ["Récords del mundo de media", "Muy llano", "Puede hacer humedad"],
    website: "https://www.valenciaciudaddelrunning.com",
  },
  {
    id: "barcelona-media",
    name: "eDreams Mitja Marató Barcelona",
    city: "Barcelona",
    country: "España",
    distanceKm: H,
    month: 2,
    typicalDate: "2027-02-14",
    elevationGainM: 40,
    elevationLossM: 40,
    temperatureC: 11,
    profile: "muy rápido",
    highlights: ["Una de las medias más rápidas de Europa", "Junto al mar"],
    website: "https://www.edreamsmitjabarcelona.com",
  },
  {
    id: "madrid-media",
    name: "Medio Maratón de Madrid",
    city: "Madrid",
    country: "España",
    distanceKm: H,
    month: 3,
    typicalDate: "2027-03-28",
    elevationGainM: 180,
    elevationLossM: 180,
    temperatureC: 12,
    profile: "ondulado",
    highlights: ["Recorrido urbano con repechos", "Altitud ~650 m"],
    website: "https://www.mediomaratonmadrid.es",
  },
  {
    id: "granada-media",
    name: "Media Maratón Ciudad de Granada",
    city: "Granada",
    country: "España",
    distanceKm: H,
    month: 4,
    // 2026 fue el sábado 25 de abril; la fecha de 2027 aún no está publicada (estimada)
    typicalDate: "2027-04-24",
    elevationGainM: 230,
    elevationLossM: 230,
    temperatureC: 18,
    profile: "exigente",
    highlights: [
      "Sábado por la tarde: salida a las 19:30 en C/ Poeta Manuel de Góngora, meta en el Palacio de Congresos",
      "Una sola vuelta por Arabial, Camino de Ronda, Av. de Pulianas y Ctra. de Murcia",
      "Subidas duras por la Cuesta del Chapiz (Albaicín) y la Cuesta de Gomérez (Alhambra): guarda fuerzas",
      "Bajada final por la Acera del Darro y el Paseo del Violón",
      "Avituallamientos en km 6; 9,5; 11,8; 14,5; 15,5; 18,7 y meta",
      "Altitud ~700 m y hora de cena: entrena alguna tirada por la tarde",
    ],
    website: "https://mediamaraton.granada.org",
  },
  {
    id: "behobia",
    name: "Behobia – San Sebastián",
    city: "Irún → San Sebastián",
    country: "España",
    distanceKm: 20,
    month: 11,
    typicalDate: "2026-11-08",
    elevationGainM: 290,
    elevationLossM: 300,
    temperatureC: 12,
    profile: "exigente",
    highlights: ["Clásica centenaria", "Subidas de Gaintxurizketa y Miracruz", "Ambiente único"],
    website: "https://www.behobia-sansebastian.com",
  },
  {
    id: "san-silvestre-vallecana",
    name: "San Silvestre Vallecana",
    city: "Madrid",
    country: "España",
    distanceKm: 10,
    month: 12,
    typicalDate: "2026-12-31",
    elevationGainM: 70,
    elevationLossM: 100,
    temperatureC: 6,
    profile: "ondulado",
    highlights: ["La carrera más popular del año", "Final en cuesta en Vallecas", "Salida masiva: cuesta ir a ritmo"],
    website: "https://www.sansilvestrevallecana.com",
  },
  {
    id: "valencia-10k",
    name: "10K Valencia Ibercaja",
    city: "Valencia",
    country: "España",
    distanceKm: 10,
    month: 1,
    typicalDate: "2027-01-10",
    elevationGainM: 15,
    elevationLossM: 15,
    temperatureC: 10,
    profile: "muy rápido",
    highlights: ["Récords del mundo de 10K", "Ideal para marca"],
    website: "https://www.10kvalencia.com",
  },
  {
    id: "parkrun-5k",
    name: "parkrun 5K",
    city: "Cualquier ciudad",
    country: "Internacional",
    distanceKm: 5,
    month: 0,
    elevationGainM: 20,
    elevationLossM: 20,
    temperatureC: 12,
    profile: "rápido",
    highlights: ["Gratis, cada sábado", "Perfecta para test de forma"],
    website: "https://www.parkrun.com",
  },
];

export function findRace(id: string | undefined): Race | undefined {
  return RACES.find((r) => r.id === id);
}

export const PROFILE_TONE: Record<Race["profile"], string> = {
  "muy rápido": "text-emerald-400 bg-emerald-400/10",
  rápido: "text-sky-400 bg-sky-400/10",
  ondulado: "text-amber-400 bg-amber-400/10",
  exigente: "text-rose-400 bg-rose-400/10",
};
